apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: calendar-app
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-app
      service: rabbitmq
  template:
    metadata:
      labels:
        app: calendar-app
        service: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.rabbitmq.user }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.rabbitmq.password }}"
          ports:
            - containerPort: 5672
            - containerPort: 15672

