apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: "{{ .Values.scheduler.image }}"
        env:
        - name: DB_USER
          value: "{{ .Values.db.user }}"
        - name: DB_PASSWORD
          value: "{{ .Values.db.password }}"
        - name: DB_NAME
          value: "{{ .Values.db.name }}"
        - name: DB_HOST
          value: "{{ .Values.db.host }}"
        - name: DB_PORT
          value: "{{ .Values.db.port }}"
        - name: RABBIT_USER
          value: "{{ .Values.rabbitmq.username }}"
        - name: RABBIT_PASSWORD
          value: "{{ .Values.rabbitmq.password }}"
        - name: RABBIT_HOST
          value: "{{ .Values.rabbitmq.host }}"
        - name: RABBIT_PORT
          value: "{{ .Values.rabbitmq.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: scheduler

