interval = 10
clearInterval = 365

[logger]
level = "INFO"

[db]
user = "${DB_USER}"
password = "${DB_PASSWORD}"
name = "${DB_NAME}"
host = "${DB_HOST}"
port = "${DB_PORT}"

[queue]
user = "${RABBIT_USER}"
password = "${RABBIT_PASSWORD}"
host = "${RABBIT_HOST}"
port = "${RABBIT_PORT}"
