storage = "sql"

[logger]
level = "INFO"

[db]
user = "postgres"
password = "postgres"
name = "postgres"
host = "localhost"
port = "5432"

[server]
host = "localhost"
port = "8080"

[grpc]
host = "localhost"
port = "50051"
