storage = "sql"

[logger]
level = "INFO"

[db]
user = "${DB_USER}"
password = "${DB_PASSWORD}"
name = "${DB_NAME}"
host = "${DB_HOST}"
port = "${DB_PORT}"

[server]
host = "${REST_HOST}"
port = "${REST_PORT}"

[grpc]
host = "${GRPC_HOST}"
port = "${GRPC_PORT}"
