// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/AndreyChufelin/homework/hw12_13_14_15_calendar/internal/storage"

	time "time"
)

// Application is an autogenerated mock type for the Application type
type Application struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, event
func (_m *Application) CreateEvent(ctx context.Context, event storage.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteEvent provides a mock function with given fields: ctx, id
func (_m *Application) DeleteEvent(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditEvent provides a mock function with given fields: ctx, id, event
func (_m *Application) EditEvent(ctx context.Context, id string, event storage.Event) error {
	ret := _m.Called(ctx, id, event)

	if len(ret) == 0 {
		panic("no return value specified for EditEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, storage.Event) error); ok {
		r0 = rf(ctx, id, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEvent provides a mock function with given fields: ctx, id
func (_m *Application) GetEvent(ctx context.Context, id string) (*storage.Event, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *storage.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.Event, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.Event); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsListDay provides a mock function with given fields: ctx, date
func (_m *Application) GetEventsListDay(ctx context.Context, date time.Time) ([]storage.Event, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsListDay")
	}

	var r0 []storage.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]storage.Event, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []storage.Event); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsListMonth provides a mock function with given fields: ctx, date
func (_m *Application) GetEventsListMonth(ctx context.Context, date time.Time) ([]storage.Event, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsListMonth")
	}

	var r0 []storage.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]storage.Event, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []storage.Event); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsListWeek provides a mock function with given fields: ctx, date
func (_m *Application) GetEventsListWeek(ctx context.Context, date time.Time) ([]storage.Event, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsListWeek")
	}

	var r0 []storage.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]storage.Event, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []storage.Event); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewApplication creates a new instance of Application. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *Application {
	mock := &Application{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
